package com.eric.mtgproject.db;
// Generated 2-Nov-2016 6:27:46 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Cardset generated by hbm2java
 */
@Entity
@Table(name = "CARDSET", catalog = "mtg")
public class Cardset implements java.io.Serializable {

	private CardsetId id;

	public Cardset() {
	}

	public Cardset(CardsetId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "setCode", column = @Column(name = "SetCode")),
			@AttributeOverride(name = "booster", column = @Column(name = "Booster")),
			@AttributeOverride(name = "border", column = @Column(name = "Border")),
			@AttributeOverride(name = "code", column = @Column(name = "Code")),
			@AttributeOverride(name = "gathererCode", column = @Column(name = "GathererCode")),
			@AttributeOverride(name = "magicCardsInfoCode", column = @Column(name = "MagicCardsInfoCode")),
			@AttributeOverride(name = "name", column = @Column(name = "Name")),
			@AttributeOverride(name = "oldCode", column = @Column(name = "OldCode")),
			@AttributeOverride(name = "releaseDate", column = @Column(name = "ReleaseDate")),
			@AttributeOverride(name = "setType", column = @Column(name = "SetType")) })
	public CardsetId getId() {
		return this.id;
	}

	public void setId(CardsetId id) {
		this.id = id;
	}

}
