package com.eric.mtgproject.db;
// Generated 2-Nov-2016 6:27:46 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CardsetId generated by hbm2java
 */
@Embeddable
public class CardsetId implements java.io.Serializable {

	private String setCode;
	private String booster;
	private String border;
	private String code;
	private String gathererCode;
	private String magicCardsInfoCode;
	private String name;
	private String oldCode;
	private String releaseDate;
	private String setType;

	public CardsetId() {
	}

	public CardsetId(String setCode, String booster, String border, String code, String gathererCode,
			String magicCardsInfoCode, String name, String oldCode, String releaseDate, String setType) {
		this.setCode = setCode;
		this.booster = booster;
		this.border = border;
		this.code = code;
		this.gathererCode = gathererCode;
		this.magicCardsInfoCode = magicCardsInfoCode;
		this.name = name;
		this.oldCode = oldCode;
		this.releaseDate = releaseDate;
		this.setType = setType;
	}

	@Column(name = "SetCode")
	public String getSetCode() {
		return this.setCode;
	}

	public void setSetCode(String setCode) {
		this.setCode = setCode;
	}

	@Column(name = "Booster")
	public String getBooster() {
		return this.booster;
	}

	public void setBooster(String booster) {
		this.booster = booster;
	}

	@Column(name = "Border")
	public String getBorder() {
		return this.border;
	}

	public void setBorder(String border) {
		this.border = border;
	}

	@Column(name = "Code")
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "GathererCode")
	public String getGathererCode() {
		return this.gathererCode;
	}

	public void setGathererCode(String gathererCode) {
		this.gathererCode = gathererCode;
	}

	@Column(name = "MagicCardsInfoCode")
	public String getMagicCardsInfoCode() {
		return this.magicCardsInfoCode;
	}

	public void setMagicCardsInfoCode(String magicCardsInfoCode) {
		this.magicCardsInfoCode = magicCardsInfoCode;
	}

	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "OldCode")
	public String getOldCode() {
		return this.oldCode;
	}

	public void setOldCode(String oldCode) {
		this.oldCode = oldCode;
	}

	@Column(name = "ReleaseDate")
	public String getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(String releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Column(name = "SetType")
	public String getSetType() {
		return this.setType;
	}

	public void setSetType(String setType) {
		this.setType = setType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CardsetId))
			return false;
		CardsetId castOther = (CardsetId) other;

		return ((this.getSetCode() == castOther.getSetCode()) || (this.getSetCode() != null
				&& castOther.getSetCode() != null && this.getSetCode().equals(castOther.getSetCode())))
				&& ((this.getBooster() == castOther.getBooster()) || (this.getBooster() != null
						&& castOther.getBooster() != null && this.getBooster().equals(castOther.getBooster())))
				&& ((this.getBorder() == castOther.getBorder()) || (this.getBorder() != null
						&& castOther.getBorder() != null && this.getBorder().equals(castOther.getBorder())))
				&& ((this.getCode() == castOther.getCode()) || (this.getCode() != null && castOther.getCode() != null
						&& this.getCode().equals(castOther.getCode())))
				&& ((this.getGathererCode() == castOther.getGathererCode())
						|| (this.getGathererCode() != null && castOther.getGathererCode() != null
								&& this.getGathererCode().equals(castOther.getGathererCode())))
				&& ((this.getMagicCardsInfoCode() == castOther.getMagicCardsInfoCode())
						|| (this.getMagicCardsInfoCode() != null && castOther.getMagicCardsInfoCode() != null
								&& this.getMagicCardsInfoCode().equals(castOther.getMagicCardsInfoCode())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getOldCode() == castOther.getOldCode()) || (this.getOldCode() != null
						&& castOther.getOldCode() != null && this.getOldCode().equals(castOther.getOldCode())))
				&& ((this.getReleaseDate() == castOther.getReleaseDate())
						|| (this.getReleaseDate() != null && castOther.getReleaseDate() != null
								&& this.getReleaseDate().equals(castOther.getReleaseDate())))
				&& ((this.getSetType() == castOther.getSetType()) || (this.getSetType() != null
						&& castOther.getSetType() != null && this.getSetType().equals(castOther.getSetType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSetCode() == null ? 0 : this.getSetCode().hashCode());
		result = 37 * result + (getBooster() == null ? 0 : this.getBooster().hashCode());
		result = 37 * result + (getBorder() == null ? 0 : this.getBorder().hashCode());
		result = 37 * result + (getCode() == null ? 0 : this.getCode().hashCode());
		result = 37 * result + (getGathererCode() == null ? 0 : this.getGathererCode().hashCode());
		result = 37 * result + (getMagicCardsInfoCode() == null ? 0 : this.getMagicCardsInfoCode().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getOldCode() == null ? 0 : this.getOldCode().hashCode());
		result = 37 * result + (getReleaseDate() == null ? 0 : this.getReleaseDate().hashCode());
		result = 37 * result + (getSetType() == null ? 0 : this.getSetType().hashCode());
		return result;
	}

}
